### ISSUE TITLE
пункты про конфиденциальность- контекст

### ISSUE THREAD

**Issue by lyubovnaboka** [synapse-studio/dogovor#12]
необходимость пунктов про конфиденциальность 
пункты про конфиденциальность 
1.
Стороны обязуются сохранять в тайне и считать конфиденциальными условия настоящего договора
оферты, полученную в процессе исполнения настоящего договора информацию о коммерческой деятельности
любой из Сторон, а также всю информацию, переданную одной Стороной другой Стороне, и обозначенную
передающей Стороной как конфиденциальная информация передающей Стороны (далее - «Конфиденциальная
Информация»), и не раскрывать, не разглашать, не опубликовывать, или иным способом не предоставлять такую
информацию какой-либо третьей стороне без предварительного письменного разрешения передающей Стороны.
2. Каждая из Сторон предпримет все необходимые меры для защиты Конфиденциальной Информации как
минимум с такой же степенью тщательности, с какой она защищает собственную конфиденциальную информацию.
Доступ к Конфиденциальной Информации будет предоставлен только тем сотрудникам каждой из Сторон, которым
он обоснованно необходим для выполнения служебных обязанностей, связанных с исполнением настоящего
договора оферты.
3. Конфиденциальная Информация всегда остается собственностью передающей Стороны и не должна
копироваться или иным способом воспроизводиться без предварительного письменного согласия передающей
Стороны.
4.
Обязательство сохранять в тайне Конфиденциальную Информацию передающей Стороны не
распространяется на информацию, которая: на момент раскрытия являлась или стала всеобщим достоянием, иначе
как вследствие нарушения, допущенного принимающей Стороной; или становится известной принимающей
Стороне из источника, иного, чем передающая Сторона, без нарушения принимающей Стороной условий
настоящего договора оферты, что может быть удостоверено документами, достаточными для подтверждения того,
что источником получения Конфиденциальной Информации является третья сторона; или была известна
принимающей Стороне до ее раскрытия по настоящему договору, что подтверждается документами, достаточными
для установления факта обладания Конфиденциальной Информацией; или была раскрыта с письменного
разрешения передающей Стороны.
5.
Обязательство сохранять в тайне Конфиденциальную Информацию в соответствии с условиями
настоящего пункта 7 вступает в силу с момента подписания настоящего договора обеими Сторонами и остается в
силе в течение 3 (Трех) лет с момента окончании срока действия настоящего договора оферты или его расторжения
по какой-либо причине.

или так:
Компания обязуется сохранять конфиденциальность информации Рекламодателя, полученную при регистрации.

**Comment by lyubovnaboka** [comment]
вот этот ещё пункт понравился 

 Компания гарантирует конфиденциальность в отношении персональных данных Клиента и предоставляет
доступ к персональным данным только тем сотрудникам, которым эта инфо

**Comment by syn-lawyer** [comment]
Давайте оценим, нужно ли нагружать договор этими пунктами? Во-первых, мы принимаем на себя дополнительные обязательства, которые нужно будет исполнять... А во-вторых, у нас договор публичный, он размещен на сайте, скрывать нам абсолютно нечего, а вот информация Клиента - это объект защиты.
Поэтому - мое мнение: не нужно нагружать договор, не нужно налагать на себя дополнительные обязательства.
