### ISSUE TITLE
ответственность за логины и пароли РК- контекст

### ISSUE THREAD

**Issue by lyubovnaboka** [synapse-studio/dogovor#13]
Добавить надо бы
Исполнитель не несёт ответственности в случае использования логина и пароля аккаунта Рекламодателя третьими лицами. Рекламодатель обязуется принять необходимые меры для сохранности своего логина и пароля.

**Comment by syn-lawyer** [comment]
У нас про логин и пароль только в п. 4.2.5.
Больше нигде ничего и не сказано, что кто-то кому то передает логин и пароль, тем более ранее это реализовано было (если мне память не изменяет) через прямую ссылку, которая приходила на электронку. 
Прошу дополнительно подумать: нужно это включать или нет? Если нужно, то куда? И как фактически обстоят дела: если логин и пароль передается, то, вероятно, нужно не только это условие вписывать, но и порядок передачи (кто, кому и в каких случаях).

**Comment by politsin** [comment]
Есть ссылка в личный кабинет (biz-panel.com) - она приходит на почту.
Кроме этого для клиента заводим учётные записи в Google/Yandex и передаём ему эти данные, чтобы можно было наблюдать за нашей работой.
