### ISSUE TITLE
Сайт - услуга или работа?

### ISSUE THREAD

**Issue by politsin** [synapse-studio/dogovor#17]
Коллеги подсказывают:
От услуги можно отказаться, а от работы - нет, должен оплатить фактически выполненный объем.
Поэтому у нас "Договор подряда на выполнение работ по..."

**Comment by syn-lawyer** [comment]
В принципе да, в "Услугах" нельзя прописывать запрет на односторонний отказ, а в "Подряде" можно. 
Но по факту: в большей своей части услуги Синапс - это все таки услуги. 
Настаивание на том, что это работа приведет к необходимости превращать результат работ в материальный вид. 
Предлагаю оставить Услуги. 

Нормы права:
**Статья 717.** Отказ заказчика от исполнения договора подряда

Если иное не предусмотрено договором подряда, заказчик может в любое время до сдачи ему результата работы отказаться от исполнения договора, уплатив подрядчику часть установленной цены пропорционально части работы, выполненной до получения извещения об отказе заказчика от исполнения договора. Заказчик также обязан возместить подрядчику убытки, причиненные прекращением договора подряда, в пределах разницы между ценой, определенной за всю работу, и частью цены, выплаченной за выполненную работу.

ст. 717, "Гражданский кодекс Российской Федерации (часть вторая)" от 26.01.1996 N 14-ФЗ (ред. от 05.12.2017) {КонсультантПлюс}

**Статья 782.** Односторонний отказ от исполнения договора возмездного оказания услуг

1. Заказчик вправе отказаться от исполнения договора возмездного оказания услуг при условии оплаты исполнителю фактически понесенных им расходов.
2. Исполнитель вправе отказаться от исполнения обязательств по договору возмездного оказания услуг лишь при условии полного возмещения заказчику убытков.

ст. 782, "Гражданский кодекс Российской Федерации (часть вторая)" от 26.01.1996 N 14-ФЗ (ред. от 05.12.2017) {КонсультантПлюс}

**Comment by politsin** [comment]
👍
