### ISSUE TITLE
Контекст - пени и работа без предварительной оплаты (от дмирия)

### ISSUE THREAD

**Issue by politsin** [synapse-studio/dogovor#2]
Из письма дмитрия от 4 августа 2016 г. : И пункт про пени предлагаю исключить и прописать что ни одна из сторон не работает без предварительной оплаты, соответсвенно просрочка по оплате появиться не сможет.

**Comment by syn-lawyer** [comment]
В договоре Контекст не нашел вообще упоминание про пени и/или неустойку. 
Думаю эта правка была уже внесена ранее или я неправильно понял задачу.
