### ISSUE TITLE
Хостинг - персональные данные

### ISSUE THREAD

**Issue by politsin** [synapse-studio/dogovor#5]
Добавить явную информацию на запрет передачи нам и хранении на сайте персональных данных.

**Comment by syn-lawyer** [comment]
Пункты 7.9. и 7.10 наоборот Заказчик дает согласие на обработку...
Или это про другое? Прошу уточнить задачу.

Спасибо.

**Comment by politsin** [comment]
Есть условынй заказчик, у него есть персональные данные своих клиентов (ексель на 1000 телефонов). И они хотят хранить их на хостинге - передача ПД нам. По стандартному договору думаю стоит явно указать, что мы даём площадку без этой истории про ПД и можем делать что хотим (например бекапить забугор).
А если вы хотите положить туда ексель с ПД и чтобы всё было по закону - давайте обсуждать и видимо делать доп-соглашение.

**Comment by politsin** [comment]
https://github.com/synapse-studio/dogovor/blob/master/Dogovor-Hosting.md тут есть этот пункт: 
7.10. Заказчик самостоятельно обрабатывает персональные данные посетителей сайта, а также клиентов сайта и несет ответственность за правомерность такой обработки. Исполнитель не имеет доступа к персональным данным посетителей сайта Заказчика и не осуществляет их обработку ни в каком виде.
